apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paybox-pgadmin-pvc
  namespace: group-5-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: paybox-pgadmin-dev-pv
  storageClassName: paybox-local-storage
