apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paybox-postgres-pvc
  namespace: group-5-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: paybox-postgres-dev-pv
  storageClassName: paybox-local-storage
