apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-argo-deployment
spec:
  selector:
    matchLabels:
      app: pgadmin-argo
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin-argo
    spec:
      containers:
        - name: pgadmin4-argo-container
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: pgadmin-secret
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: PGADMIN_PORT
              value: "80"
          ports:
            - containerPort: 80
