apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paybox-postgres-pvc-argo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: paybox-postgres-pv-argo
  storageClassName: paybox-local-storage-argo
