apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sts
  namespace: group-5-dev
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeName: node55874-tcc-01.th1.proen.cloud
      containers:
        - name: mongodb-container
          image: mongo:7
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
          env:
            - name: TZ
              value: Asia/Bangkok
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-vol
      volumes:
        - name: mongodb-vol
          persistentVolumeClaim:
            claimName: paybox-mongodb-pvc
