apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: group-5-dev
  labels:
    app: mongo-express
spec:
  type: ClusterIP
  ports:
    - port: 8081
  selector:
    app: mongo-express
