apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: group-5-dev
  labels:
    app: mongodb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
  selector:
    app: mongodb
