kind: PersistentVolume
apiVersion: v1
metadata:
  name: paybox-mongodb-dev-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: paybox-local-storage
  hostPath:
    path: /opt/app/group-5-paybox/dev/mongodb
