apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationapi-deployment
  namespace: group-5-dev
  labels:
    app: authenticationapi
spec:
  selector:
    matchLabels:
      app: authenticationapi
  template:
    metadata:
      labels:
        app: authenticationapi
    spec:
      containers:
        - name: authenticationapi-container
          image: "jirasinm/tcc-group-5-auth:dev-60bdb60"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          ports:
            - containerPort: 5001
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: DATABASE_URL
              value: "postgres://paybox:group-5@postgres-service:5432/paybox"
            - name: JWT_EXPIRE
              value: 1d
            - name: JWT_SECRET_KEY
              value: G5aIoG4QG1rLZ6qyv6RLTSggT7Tno8XH
            - name: PORT
              value: "5001"
