apiVersion: v1
kind: Service
metadata:
  name: authenticationapi-argo-service
  labels:
    app: authenticationapi-argo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    app: authenticationapi-argo
