apiVersion: v1
kind: Service
metadata:
  name: authenticationapi
  labels:
    app: authenticationapi
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    app: authenticationapi
