apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: group-5-prod
  labels:
    app: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express4-container
          image: mongo-express:1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "example"
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://mongodb-service:27017"
