apiVersion: v1
kind: Service
metadata:
  namespace: group-5-paybox
  name: payment
  labels:
    app: payment
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: payment
