apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: group-5-paybox
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment4
          image: zaserzafear/tcc-group-5-paybox-payment
          imagePullPolicy: "IfNotPresent"
          env:
            - name: TZ
              value: Asia/Bangkok
          ports:
            - containerPort: 3000
