apiVersion: apps/v1
kind: Deployment
metadata:
  name: webadmin-deployment
  namespace: group-5-dev
spec:
  selector:
    matchLabels:
      app: webadmin
  template:
    metadata:
      labels:
        app: webadmin
    spec:
      containers:
        - name: webadmin-container
          image: zaserzafear/paybox-webadmin:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: BASE_PATH
              value: /group-5-dev/webadmin
            - name: API_URL
              value: http://authenticationapi-service
            - name: NEXTAUTH_SECRET
              value: +bTDE5JaAmoJL+uu/C7h8RjiGA/+4iTrObR9N+W6juY=
