apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webadmin-hpa
  namespace: group-5-dev
  labels:
    app: webadmin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webadmin-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
