apiVersion: v1
kind: Service
metadata:
  name: webadmin-service
  labels:
    app: webadmin
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: webadmin
