import { Inter } from 'next/font/google'
import './globals.css'
import { CustomProvider } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <CustomProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </CustomProvider>
  )
}
