apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: statementapi-hpa
  namespace: group-5-prod
  labels:
    app: statementapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: statementapi-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
