apiVersion: v1
kind: Service
metadata:
  name: statementapi-service
  namespace: group-5-prod
  labels:
    app: statementapi
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: statementapi
