apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: group-5-prod
  labels:
    app: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      nodeName: node53272-tcc-01.th1.proen.cloud
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 5050:5050 /var/lib/pgadmin"]
          volumeMounts:
            - name: pgadmin-vol
              mountPath: /var/lib/pgadmin
      containers:
        - name: pgadmin4-container
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: pgadmin-secret
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: PGADMIN_PORT
              value: "80"
          volumeMounts:
            - name: pgadmin-vol
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-vol
          persistentVolumeClaim:
            claimName: paybox-pgadmin-pvc
