apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: group-5-prod
  labels:
    app: pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: support@paybox.com
  PGADMIN_DEFAULT_PASSWORD: group-5
