apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: group-5-prod
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: postgres
