apiVersion: apps/v1
kind: Deployment
metadata:
  name: statementapi-deployment
  namespace: group-5-dev
  labels:
    app: statementapi
spec:
  selector:
    matchLabels:
      app: statementapi
  template:
    metadata:
      labels:
        app: statementapi
    spec:
      containers:
        - name: statementapi-container
          image: zaserzafear/tcc-01-statement-api:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: DATABASE_URL
              value: "mongodb://mongodb-service:27017"
            - name: PORT
              value: "8000"
