import { Inter } from 'next/font/google'
import './globals.css'
import { CustomProvider } from './provider'
import StyledComponentsRegistry from '@/src/lib/AntdRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <CustomProvider>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </body>
      </html>
    </CustomProvider>
  )
}
