name: Update Auth Deployment

on:
  push:
    paths:
      - 'application/paybox-auth-api/**'
  workflow_dispatch:

jobs:
  deployment-auth:
    uses: the-cloud-camp/tcc-group-5/.github/workflows/update-deployment-template.yaml@develop
    with:
      APP_FOLDER: paybox-auth-api
      SERVICE_NAME: auth
      APP_MANIFEST_FOLDER: authenticationapi