# name: ci

# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           tags: zaserzafear/tcc-group-5-paybox-payment:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: docker
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Install kubectl
#         run: |
#           sudo apt-get update && sudo apt-get install -y kubectl

#       - name: Update Kubernetes Deployment
#         run: kubectl set image deployment/your-deployment-name your-container-name=user/app:latest
#         env:
#           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
