name: Update Prod Deployment Frontend

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
    paths:
      - 'application/paybox-next/package.json'
  workflow_dispatch:

jobs:
  version-frontend:
    uses: the-cloud-camp/tcc-group-5/.github/workflows/prod-template.yaml@main
    with:
      APP_FOLDER: paybox-next
      SERVICE_NAME: webadmin
      APP_MANIFEST_FOLDER: webadmin