name: Update Prod Deployment Auth

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
    paths:
      - 'application/paybox-auth-api/package.json'
  workflow_dispatch:

jobs:
  version-frontend:
    uses: the-cloud-camp/tcc-group-5/.github/workflows/prod-template.yaml@develop
    with:
      APP_FOLDER: paybox-auth-api
      SERVICE_NAME: auth
      APP_MANIFEST_FOLDER: authenticationapi
    secrets: inherit