name: PR

on:
  push:
    branches:
      - workflow
  pull_request:
    types: 
      - closed
    branches: 
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./application

jobs:
  image-tag:
    if: github.event.pull_request.merged == true
    name: Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Image
        continue-on-error: true
        run: |
          git --version
          git branch -a
          git checkout -f develop
          git show HEAD | grep commit | head -n 1 | cut -d " " -f 2
          IMAGE_TAG=$(git log -1 | grep commit | head -n 1 | cut -d " " -f 2)
          echo "Docker Login"
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker pull ${{vars.APP_IMAGE}}/auth:$IMAGE_TAG
          echo "List Images"
          docker images
