name: Update Version

on:
  push:
    tags:
      - v*
    branches:
      - workflo
  workflow_dispatch:

env:
  VERSION_FILE: test-package.json

defaults:
  run:
    working-directory: ./application

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Check Current Version
        run: |
          CURRENT_VERSION=$(yq -oy '.version' $VERSION_FILE)
          echo "CURRENT_VERSION=$CURRENT_VERSION"
          echo "CURRENT_VERSION_2=$(yq -oy '.version' $VERSION_FILE)"

          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION_2=$(yq -oy '.version' $VERSION_FILE)" >> $GITHUB_ENV

          echo "MAJOR=$(echo $CURRENT_VERSION | cut -d "." -f 1)" >> $GITHUB_ENV
          echo "MINOR=$(echo $CURRENT_VERSION | cut -d "." -f 2)" >> $GITHUB_ENV
          echo "BUILD=$(echo $CURRENT_VERSION | cut -d "." -f 3)" >> $GITHUB_ENV

      - name: Update Version
        run: |
          echo $CURRENT_VERSION
          echo $CURRENT_VERSION_2

          COMMIT_CONVENTION=$(git log -1 --format%s | cut -d ":" -f 1)
          echo "COMMIT_CONVENTION is $COMMIT_CONVENTION"

          if [[ "$COMMIT_CONVENTION" == "feat" ]]; then
            echo "this feat"
