name: Update Auth Version

on:
  pull_request:
    types: [closed]
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  version-frontend:
    if: contains(github.head_ref, 'front')
    uses: the-cloud-camp/tcc-group-5/.github/workflows/version.yaml@develop
    with:
      APP_PATH: paybox-next

  version-auth:
    if: contains(github.head_ref, 'auth')
    uses: the-cloud-camp/tcc-group-5/.github/workflows/version.yaml@develop
    with:
      APP_PATH: paybox-auth-api