apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authenticationapi-hpa
  namespace: group-5-prod
  labels:
    app: authenticationapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authenticationapi-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
