apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authenticationapi-argo-hpa-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authenticationapi-argo-deployment-prod
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
